M48
; DRILL file {KiCad 7.0.8-dirty} date Thu Nov 16 23:27:07 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-16T23:27:07-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-dirty
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X139.026Y-116.59
X139.296Y-52.6
X183.026Y-116.59
X183.186Y-52.6
T0
M30
